### ISSUE TITLE
Starting RhubarbVR with the Varjo Base installed, but no headset connected, causes the engine to hang on startup

### ISSUE THREAD

**Issue by dfgHiatus** [RhubarbVR/RhubarbVR#17]
**Describe the bug**
Starting RhubarbVR with the Varjo Base installed (version 3.5 at the time of writing this) causes the engine to hang on startup.

**To Reproduce**
1. Install the Varjo Base. 
2. Start RhubarbVR without a Varjo headset connected.
3. Observe the engine hangs with the message ```[Varjo::HandTrackingClient::process] (skipped 0) Waiting for IPC input Varjo.HandTracking.TrackedHands connection...``` repeating over and over.

**Expected behavior**
The engine starts as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/51272212/175396939-569a3360-137a-478a-8b77-df9fed7e9a77.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Faolan-Rad** [comment]
That is more of a stereo kit problem so varjo users might have to use the unity build

**Comment by Faolan-Rad** [comment]
Closing cuz rhubarb is no longer using stereo kit
