### ISSUE TITLE
Web-UI as primary user-interface

### ISSUE THREAD

**Issue by Reiko9** [RhubarbVR/RhubarbVR#25]
Webpages on the In-game browser running as Local could communicate with the Game engine through protocols such as Websockets, WebRTC, and HTTP 2 to provide Navigation, file-browser, volume control / volume visualization and other key features.

Iframes on webpages could be a way of easily adding community generated webpage tools / features to an existing dash board.

Simplistic commands sent from the web-browser would be read by the game engine to enact those key behaviors and the game-engine sends commands back to the browser to display output data and affect operation state.

These commands can be thought of as text-messages between the browser and engine, and here are a few I dreamed up:
(30 is used as an example value to be passed....  (Function pointers I believe can be used to load code associated with processing these instructions)  (Abbreviated forms of each instruction are on the right, the more frequently the instruction is  
                                                  sent, the more effect on bandwidth/performance every character has)

############################################################################################
**(game-engine to browser UI instruction examples)    (game ==> browser UI)**

local_microphone_intensity:30;     #####     lmi:30;

local_speaker_intensity:30;       ######         lsi:30;

local_speaker_devices:device_name:device_name;      ####      lsd:device_name:device_name; 

local_microphone_devices:device_name:device_name;  ####  lmd:device_name:device_name; 

list_directory_contents:cow.gif:car.png:myfolder.folder;    #####  ldc:cow.gif:car.png:myfolder.folder;  
(World browsing and item inventory can be treated like file directories) (.folder extension identifies a folder)                                                                                                           

send_link:file:///home/66.jpg:file:///home/george.jpg;  #####   sl:\~/66.jpg:~/george.jpg;
( ~ on linux is home directory, so default directory specified would make sense)

send_raw_data:dGhpcyBpcyBhIHRlc3Rpbmc;  (Base64 Data) #### srd:dGhpcyBpcyBhIHRlc3Rpbmc;

private_message:Hello here is a test message;  #### pm:Hello here is a test message;  

error_message:Session-Join-Failed Error 404;   #### em:Session-Join-Failed Error 404;  (unique style different than pm)

warning_message:session at max users;        #####    wm:session at max users;  (probably less menacing style than em)

selected_object_ID:item/object ID;   ####  soi:item/object ID;   (Used so the GUI can save items to inventory and provide info)

############################################################################################
**browser UI to game engine instruction examples (Browser UI ==> game)**

spawn_item_url:Path_to_Item;    ####     siu:Path_to_Item              (If World-permissions permit allows spawning items by url)

enter_avatar:path_to_avatar;    ####      ea:Path_to_avatar;           (Swaps the users avatar to selected one)

get_item:item/object ID;  ####   gi:item/object ID;   (If Browser UI has a button to add an item to inventory)

set_speaker_device:device_name;      ####  ssd:device_name;                                                                                              

set_microphone_device:device_name;   ####    smd:device_name;

I figure performance is probably high enough to use the Non abbreviated names on the left, which should be easy to read and debug, because you know exactly what the command is telling the browser or game-engine to do.

(This command system will make Permissions quite simple, since all you have to do is ignore unauthorized commands from the browser.)

The instruction set of course needs plenty of cleaning and expansion, but I hope the simplicity and true potential is now visible.

(I do wonder if smaller browser window tiles could even be used for tools, object inspection, and stuff not a part of the dash)

**Comment by Reiko9** [comment]
Instruction sets I believe are an effective means to communicate between rhubarb core and components worked on by other developers.  
  Inter-process communication may be the correct term and it is used heavily by operating systems:
https://en.wikipedia.org/wiki/Inter-process_communication

Likewise most network hardware uses ICMP messages to communicate key information and debug.... (the famous ping command is one well known ICMP message) https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol

**Comment by Faolan-Rad** [comment]
There will be a way to communicate in and out of the web browser to the rhubarb scripting language. There are no plans to make the primary UI system run in a web browser for things like the friend system or the world browser because it would have a lot of performance implications. One of those is the web browser not being able to reuse assets across tabs/UIs. Any asset that is loaded for one UI would have to be loaded into ram again for another UI to render. There are also problems with network syncing and do to it running outside the sync structure. I would also have to convert every texture into a browser readable version of the texture.
